version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"  # Web UI用
      - "3000:3000"  # MCP Server用
    volumes:
      - mcp_data:/app/data  # Docker内のデータ永続化
      - mcp_logs:/app/logs  # Docker内のログ永続化
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mcp_data:
    driver: local
  mcp_logs:
    driver: local
