version: "3.9"

services:
  mcp-server:
    build: .
    image: local-db-mcp-server-web-ui
    container_name: local-db-mcp-server-mcp-server-1
    volumes:
      - local-db-mcp-server_mcp_data:/app/data
      - local-db-mcp-server_mcp_logs:/app/logs
    command: python mcp_server.py
    ports:
      - "8000:8000"
    restart: unless-stopped
    stdin_open: true
    tty: true

  web-ui:
    build: .
    image: local-db-mcp-server-web-ui
    container_name: local-db-mcp-server-web-ui-1
    volumes:
      - local-db-mcp-server_mcp_data:/app/data
      - local-db-mcp-server_mcp_logs:/app/logs
    command: python server.py
    ports:
      - "8001:8000"
    restart: unless-stopped
    depends_on:
      - mcp-server

volumes:
  local-db-mcp-server_mcp_data:
  local-db-mcp-server_mcp_logs:
